on:
  release:
    types:
      - published

jobs:
  deploy-release:
    runs-on: ubuntu-22.04
    container:
      image: docker:23.0
    steps:
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Deploy using tag
        run: |
          docker pull ghcr.io/klawr/mqtt-inspector:latest
          docker image tag ghcr.io/klawr/mqtt-inspector:latest ghcr.io/klawr/mqtt-inspector:${{ github.ref_name }}
          docker push ghcr.io/klawr/mqtt-inspector:${{ github.ref_name }}